//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YZXDMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BFD
    {
        public int Id { get; set; }
        public Nullable<int> CarInfoID { get; set; }
        public Nullable<int> Asis { get; set; }
        public string jylsh { get; set; }
        public string jyjgbh { get; set; }
        public string jcxdh { get; set; }
        public string jyxm { get; set; }
        public string jycs { get; set; }
        public string zlz { get; set; }
        public string ylz { get; set; }
        public string qhzzdl { get; set; }
        public string qhyzdl { get; set; }
        public string qczzdl { get; set; }
        public string qcyzdl { get; set; }
        public string dll { get; set; }
        public string zdlpd { get; set; }
        public string bphl { get; set; }
        public string bphlpd { get; set; }
        public string jzzh { get; set; }
        public string jzzzdl { get; set; }
        public string jzbphl { get; set; }
        public string jzbphlpd { get; set; }
        public string zdpd { get; set; }
        public string zldtlh { get; set; }
        public string yldtlh { get; set; }
        public string zdlqx { get; set; }
        public Nullable<System.DateTime> UPD { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
