//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YZXDMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarInfo
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string JYLSH { get; set; }
        public string JYJGBH { get; set; }
        public string JCXDH { get; set; }
        public string XH { get; set; }
        public string HPZL { get; set; }
        public string HPHM { get; set; }
        public string CLSBDH { get; set; }
        public string FDJH { get; set; }
        public string CSYS { get; set; }
        public string SYXZ { get; set; }
        public Nullable<System.DateTime> CCDJRQ { get; set; }
        public Nullable<System.DateTime> JYRQ { get; set; }
        public Nullable<System.DateTime> JYYXQZ { get; set; }
        public Nullable<System.DateTime> BXZZRQ { get; set; }
        public string RLZL { get; set; }
        public Nullable<int> GL { get; set; }
        public Nullable<int> ZS { get; set; }
        public Nullable<int> ZJ { get; set; }
        public Nullable<int> QLJ { get; set; }
        public Nullable<int> HLJ { get; set; }
        public Nullable<int> ZZL { get; set; }
        public Nullable<int> ZBZL { get; set; }
        public Nullable<System.DateTime> CCRQ { get; set; }
        public string QDXS { get; set; }
        public Nullable<int> ZCZS { get; set; }
        public string ZCZW { get; set; }
        public Nullable<int> ZZS { get; set; }
        public string ZZLY { get; set; }
        public string QZDZ { get; set; }
        public string YGDDTZ { get; set; }
        public string ZXZXJXS { get; set; }
        public Nullable<int> LCBDS { get; set; }
        public string JYXM { get; set; }
        public string JYLB { get; set; }
        public string BHGX { get; set; }
        public Nullable<System.DateTime> CCDLSJ { get; set; }
        public Nullable<System.DateTime> DLSJ { get; set; }
        public Nullable<int> JYCS { get; set; }
        public string DLY { get; set; }
        public string YCY { get; set; }
        public string WJY { get; set; }
        public string DTJYY { get; set; }
        public string DPJYY { get; set; }
        public string CLPP1 { get; set; }
        public string CLXH { get; set; }
        public string SYR { get; set; }
        public string CLLX { get; set; }
        public Nullable<int> CWKC { get; set; }
        public Nullable<int> CWKK { get; set; }
        public Nullable<int> CWKG { get; set; }
        public string CLYT { get; set; }
        public string YTSX { get; set; }
        public string DLYSFZH { get; set; }
        public string YCYSFZH { get; set; }
        public string WJYSFZH { get; set; }
        public string DTJYYSFZH { get; set; }
        public string DPJYYSFZH { get; set; }
        public string CLSSLB { get; set; }
        public string JCXLB { get; set; }
        public string SJR { get; set; }
        public string SJRSFZH { get; set; }
        public Nullable<System.DateTime> UDP { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
