//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YZXDMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParkBFD
    {
        public int Id { get; set; }
        public Nullable<int> CarInfoID { get; set; }
        public string jylsh { get; set; }
        public string jyjgbh { get; set; }
        public string jcxdh { get; set; }
        public string jyxm { get; set; }
        public string jycs { get; set; }
        public string yzzczdl { get; set; }
        public string ezzczdl { get; set; }
        public string sanzzczdl { get; set; }
        public string sizzczdl { get; set; }
        public string wzzczdl { get; set; }
        public string zczczdl { get; set; }
        public string tczzdl { get; set; }
        public string tcyzdl { get; set; }
        public string tczdl { get; set; }
        public string tczdpd { get; set; }
        public Nullable<System.DateTime> UDP { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
