//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YZXDMS.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class YZXEntities : DbContext
    {
        public YZXEntities()
            : base("name=YZXEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BFD> BFD { get; set; }
        public virtual DbSet<CarInfo> CarInfo { get; set; }
        public virtual DbSet<ComplexResult> ComplexResult { get; set; }
        public virtual DbSet<ParkBFD> ParkBFD { get; set; }
        public virtual DbSet<Powers> Powers { get; set; }
        public virtual DbSet<SafaResult> SafaResult { get; set; }
        public virtual DbSet<Speed> Speed { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<WaitDetection> WaitDetection { get; set; }
    }
}
