//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YZXDMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WaitDetection
    {
        public int Id { get; set; }
        public int CarInfoId { get; set; }
        public string jylsh { get; set; }
        public Nullable<int> LineID { get; set; }
        public int Status { get; set; }
    }
}
